name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v1
    
    - name: dependencies (ubuntu and macos)
      if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' }}
      run: |
        brew install pkgconfig doctest
        brew reinstall openssl
    
    - name: dependencies (windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        choco install openssl
        vcpkg install doctest

    - name: configure
      run: cmake -Bbuild -DBUILD_TESTS=ON -DCLANG_TIDY=ON .

    - name: build
      run: cmake --build build --target SFrame

    - name: test
      run: |
        cmake --build build --target SFrameTests
        cd build
        ctest

