name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: check clang-format
      uses: jidicula/clang-format-action@master
